version: "2.2"

services:
  mysql:
    image: mariadb:10.10
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  slurmdbd:
    image: slurm-docker-cluster:${IMAGE_TAG:-21.08}
    build:
      context: .
      args:
        SLURM_TAG: ${SLURM_TAG:-slurm-23-02-6-1}
    command: [ "slurmdbd" ]
    container_name: slurmdbd
    hostname: slurmdbd
    environment:
      JWT_KEY_PATH: ${JWT_KEY_PATH:-/var/spool/slurm/statesave/jwt_hs256.key}
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
      - ${JWT_KEY_VOLUME:-}
    expose:
      - "6819"
    depends_on:
      - mysql

  slurmctld:
    image: slurm-docker-cluster:${IMAGE_TAG:-21.08}
    command: [ "slurmctld" ]
    container_name: slurmctld
    hostname: slurmctld
    environment:
      JWT_KEY_PATH: ${JWT_KEY_PATH:-/var/spool/slurm/statesave/jwt_hs256.key}
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ${JWT_KEY_VOLUME:-}
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"

  c1:
    image: slurm-docker-cluster:${IMAGE_TAG:-21.08}
    command: [ "slurmd" ]
    hostname: c1
    container_name: c1
    environment:
      JWT_KEY_PATH: ${JWT_KEY_PATH:-/var/spool/slurm/statesave/jwt_hs256.key}
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ${JWT_KEY_VOLUME:-}
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

  c2:
    image: slurm-docker-cluster:${IMAGE_TAG:-21.08}
    entrypoint: [ "sh", "-c" ]
    command: [ "/usr/share/bin/slurm-interface.sh" ]
    hostname: c2
    container_name: c2
    privileged: true
    environment:
      JWT_KEY_PATH: ${JWT_KEY_PATH:-/var/spool/slurm/statesave/jwt_hs256.key}
      SLURM_INTERFACE: ${SLURM_INTERFACE:-rest}
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ${JWT_KEY_VOLUME:-}
    expose:
      - "6818"
      - "9200"
      - "22"
    ports:
      - 9200:9200
      - ${SSH_PORT:-2222}:22
    depends_on:
      - "c1"

networks:
  default:
    name: slurm_rest_api
    driver: bridge
    
volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
